function run_live_webcam_detection_testingv2(varargin)
    % Handle optional arguments
    if nargin == 0
        % No arguments provided - load model automatically
        disp('Loading ASL CNN model...');
        
        % Try to load the model
        modelFile = 'asl_cnn_model.mat';
        if exist(modelFile, 'file')
            load(modelFile);
            if exist('aslNet', 'var')
                inputSize = aslNet.Layers(1).InputSize;
                disp(['Model loaded. Input size: ', num2str(inputSize(1)), 'x', num2str(inputSize(2))]);
            else
                error('Model file does not contain "aslNet".');
            end
        else
            error(['Model file not found: ', modelFile]);
        end
    elseif nargin == 1
        % Only network provided
        aslNet = varargin{1};
        inputSize = aslNet.Layers(1).InputSize;
    elseif nargin == 2
        % Both network and inputSize provided
        aslNet = varargin{1};
        inputSize = varargin{2};
    else
        error('Too many input arguments.');
    end
    
    % Rest of your function code here...
    % Get available cameras
    camList = webcamlist;
    
    % Create camera selection dialog
    fSelection = uifigure('Name', 'Camera Selection', 'Position', [500 400 350 200], ...
                          'Color', [0.15 0.15 0.15]);
    
    uilabel(fSelection, ...
        'Position', [20 150 310 30], ...
        'Text', 'Select Camera for Sign Language Detection', ...
        'FontSize', 16, ...
        'FontColor', 'white', ...
        'HorizontalAlignment', 'center');
    
    cameraDropdown = uidropdown(fSelection, ...
        'Position', [50 110 250 30], ...
        'Items', camList, ...
        'Value', camList{1}, ...
        'FontSize', 14);
    
    uibutton(fSelection, ...
        'Position', [50 50 250 40], ...
        'Text', 'Start Detection', ...
        'ButtonPushedFcn', @(btn,event) startDetection(), ...
        'FontSize', 16, ...
        'BackgroundColor', [0.2 0.6 0.2], ...
        'FontColor', 'white');
    
    % Wait for user selection
    uiwait(fSelection);
    
    function startDetection()
        selectedCamera = cameraDropdown.Value;
        close(fSelection);
        
        % Initialize selected webcam
        cam = webcam(selectedCamera);
        
        % Create modern dark GUI window
        f = uifigure('Name', 'Live Sign Language Detection', 'Position', [100 100 900 650], ...
                     'Color', [0.15 0.15 0.15]);
        
        % Title banner with camera info
        uilabel(f, ...
            'Position', [0 580 900 70], ...
            'Text', 'LIVE SIGN LANGUAGE DETECTION', ...
            'FontSize', 24, ...
            'FontWeight', 'bold', ...
            'FontColor', [0.2 0.8 0.9], ...
            'BackgroundColor', [0.08 0.08 0.08], ...
            'HorizontalAlignment', 'center');

        % Camera display area using uiaxes
        ax = uiaxes(f, 'Position', [30 160 500 400]);
        ax.XColor = 'none';
        ax.YColor = 'none';
        ax.Color = [0.1 0.1 0.1];
        ax.Toolbar.Visible = 'off';
        title(ax, 'Camera Output', 'Color', [0.8 0.8 0.8], 'FontSize', 16, 'FontWeight', 'bold');
        axis(ax, 'tight');

        % Results display area
        resultsContainer = uicontainer(f, ...
            'Position', [560 160 320 400], ...
            'BackgroundColor', [0.1 0.1 0.1]);
        
        % Add title for results container
        uilabel(resultsContainer, ...
            'Position', [0 380 320 20], ...
            'Text', 'Detection Results', ...
            'FontSize', 16, ...
            'FontWeight', 'bold', ...
            'FontColor', [0.8 0.8 0.8], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.1 0.1 0.1]);
        
        % Prediction display
        predictionBox = uicontainer(resultsContainer, ...
            'Position', [20 280 280 90], ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        uilabel(predictionBox, ...
            'Position', [10 55 260 25], ...
            'Text', 'PREDICTED LETTER', ...
            'FontSize', 14, ...
            'FontColor', [0.7 0.7 0.7], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        predictionLabel = uilabel(predictionBox, ...
            'Position', [10 10 260 45], ...
            'Text', '-', ...
            'FontSize', 36, ...
            'FontWeight', 'bold', ...
            'FontColor', [0.2 0.9 0.9], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        % Confidence display
        confidenceBox = uicontainer(resultsContainer, ...
            'Position', [20 180 280 80], ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        uilabel(confidenceBox, ...
            'Position', [10 45 260 25], ...
            'Text', 'CONFIDENCE LEVEL', ...
            'FontSize', 14, ...
            'FontColor', [0.7 0.7 0.7], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        confidenceLabel = uilabel(confidenceBox, ...
            'Position', [10 10 260 35], ...
            'Text', '0.0%', ...
            'FontSize', 24, ...
            'FontColor', [0.8 0.8 1], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        % Status display
        statusBox = uicontainer(resultsContainer, ...
            'Position', [20 50 280 110], ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        uilabel(statusBox, ...
            'Position', [10 80 260 25], ...
            'Text', 'SYSTEM STATUS', ...
            'FontSize', 14, ...
            'FontColor', [0.7 0.7 0.7], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        statusLabel = uilabel(statusBox, ...
            'Position', [10 45 260 35], ...
            'Text', 'Initializing...', ...
            'FontSize', 18, ...
            'FontColor', [1 0.8 0.3], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        % User guidance
        uilabel(f, ...
            'Position', [30 130 500 20], ...
            'Text', 'Position your hand in the center of the frame for best results', ...
            'FontSize', 12, ...
            'FontColor', [0.8 0.8 0.8], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', [0.15 0.15 0.15]);
        
        % Stop button
        btn = uibutton(f, ...
            'Text', 'Stop Detection', ...
            'Position', [360 80 180 50], ...
            'ButtonPushedFcn', @(btn,event) stopAndClose(), ...
            'FontSize', 16, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [0.8 0.2 0.2], ...
            'FontColor', 'white');

        % Use a local variable for the loop control
        continueLoop = true;
        
        % Initialization message
        statusLabel.Text = 'Initializing camera...';
        drawnow;
        pause(1);
        statusLabel.Text = 'Detecting...';
        statusLabel.FontColor = [0.3 0.9 0.3];
        drawnow;
        
        % Set up cleanup function
        f.CloseRequestFcn = @(src,event) cleanupAndClose();
        
        while continueLoop && isvalid(f)
            try
                % Capture frame
                frame = snapshot(cam);
                processedFrame = imresize(frame, inputSize(1:2));
                
                % Classification
                [YPred, scores] = classify(aslNet, processedFrame);
                confidence = max(scores) * 100;
                
                % Display original frame
                imshow(frame, 'Parent', ax);
                
                % Update prediction display
                predictionLabel.Text = char(YPred);
                
                % Update confidence with color coding
                confidenceLabel.Text = sprintf('%.1f%%', confidence);
                if confidence > 85
                    confidenceLabel.FontColor = [0.3 1 0.3];
                elseif confidence > 70
                    confidenceLabel.FontColor = [1 1 0.3];
                else
                    confidenceLabel.FontColor = [1 0.4 0.3];
                end
                
                drawnow limitrate;
                
            catch ME
                if contains(ME.message, 'Invalid or deleted object')
                    break;
                else
                    rethrow(ME);
                end
            end
        end

        % Function to stop detection and close figure
        function stopAndClose()
            continueLoop = false;
            
            % Update status before closing
            if isvalid(f)
                statusLabel.Text = 'Stopping...';
                statusLabel.FontColor = [1 0.5 0.3];
                drawnow;
                
                % Clean up camera
                if exist('cam', 'var') && isvalid(cam)
                    clear cam;
                end
                
                % Close the figure after a brief delay
                pause(0.5);
                delete(f);
            end
        end
        
        function cleanupAndClose()
            continueLoop = false;
            if exist('cam', 'var') && isvalid(cam)
                clear cam;
            end
            delete(f);
        end
    end
end